[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
Raycore = "afc56b53-c9a9-482a-a956-d1d800e05559"
Website = "75363ec7-b184-4002-9572-26a7eb910f3c"

[sources]
Website = {path = ".."}

[compat]
Bonito = "4.1.11"
